### PR TITLE
Julien/uist bugfix

### LINKED ISSUE #126: feedback doesn't work in "watchDemo" practice mode

### LINKED ISSUE #127: the correct practiceMode isn't selected

### PR DESCRIPTION
**Pull request by j55blanchet**
Fixing bugs for UIST:
* FIxed: Wrong Practice Activity is selected (Closes #127)
* Fixed: Feedback doesn't work when user mirror is hidden (Closes #126)
* Inproves logging to help find root cause of #120 (the try-catch mitigation is already merged).
* Adds an animation to the "Practice" button that plays whenever a different node is selected on the dance tree page. This helps signal to the user that the target of the practice button has been updated.

### CODE REVIEW

File: svelte-web-frontend/src/lib/model/PracticeActivity.ts [hunk 1]
```diff
@@ -61,8 +61,8 @@ export const PracticeInterfaceModes = {
 export type PracticeInterfaceModeKey = keyof typeof PracticeInterfaceModes;
 export const PracticeInterfaceModeOptions: Record<PracticeInterfaceModeKey, string> = {
     watchDemo: 'Demo Video',
-    userVideoOnly: 'Demo + Mirror',
-    bothVideos: 'Mirror',
+    bothVideos: 'Demo + Mirror',
```
Comment (j55blanchet) [inline svelte-web-frontend/src/lib/model/PracticeActivity.ts:64]: this was the source of the incorrect practice mode bug! Such a silly mistake.

**Review by sixuanhan — APPROVED** [review]
great work!
